name: Build Docs

concurrency:
  group: docs-build-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - '.readthedocs.yaml'
      - 'mkdocs.yml'
      - 'rtd_get_docs.py'

permissions:
  contents: read

jobs:          
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up data cache
        id: cache-data
        uses: actions/cache@v3
        with:
          path: docs/ensembl_tui_data.zip
          key: ${{ runner.os }}-data-v1-${{ hashFiles('docs/ensembl_tui_data.zip') }}
          restore-keys: |
            ${{ runner.os }}-data-v1-

      - name: Check cache status
        run: |
          echo "Cache hit: ${{ steps.cache-data.outputs.cache-hit }} ****"

      - name: Download data file
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: |
          curl -L -o docs/ensembl_tui_data.zip "https://www.dropbox.com/scl/fi/pr5y1r3abi8mam26rasg3/ensembl_tui_data.zip?rlkey=jvke75kupiugs47zjhisans38&dl=1"

      - uses: "actions/setup-python@v5"
        with:
            python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install Docs Dependencies
        run: |
          uv venv venv -p python
          source venv/bin/activate
          uv pip install ".[doc]"

      - name: Build Documentation
        run: |
          source venv/bin/activate
          # this dir needs to be in place for mkdocs to start
          mkdir -p docs/overrides
          mkdocs build
        working-directory: ${{ github.workspace }}

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ensembl_tui-docs-html
          path: site
