name: Release

on: [workflow_dispatch]

jobs:
  test:
    name: "Test on Python ${{ matrix.python-version }} (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: Set up small cache
        id: cache-small-data
        uses: actions/cache@v3
        with:
          path: tests/data
          key: ${{ runner.os }}-small-v3-${{ hashFiles('tests/data/small-115.zip') }}
          restore-keys: |
            ${{ runner.os }}-small-v3-

      - name: Check cache status
        run: |
          echo "Cache hit: ${{ steps.cache-small-data.outputs.cache-hit }} ***"

      - name: Download small data file
        if: steps.cache-small-data.outputs.cache-hit != 'true'
        run: |
          curl -L -o tests/data/small-115.zip "https://www.dropbox.com/scl/fi/cknsuhd6k8t6fjn1odzog/small-115.zip?rlkey=zkacmbhx4ssf4v80d78dd9uql&dl=1"

      - name: Set up apes installed cache
        id: cache-apes-data
        uses: actions/cache@v3
        with:
          path: tests/data
          key: ${{ runner.os }}-apes-v4-${{ hashFiles('tests/data/apes-115.zip') }}
          restore-keys: |
            ${{ runner.os }}-apes-v4-

      - name: Check apes data cache status
        run: |
          echo "Cache hit: ${{ steps.cache-apes-data.outputs.cache-hit }} ***"

      - name: Download apes installation data file
        if: steps.cache-apes-data.outputs.cache-hit != 'true'
        run: |
          curl -L -o tests/data/apes-115.zip "https://www.dropbox.com/scl/fi/h6kd0rlntvyzcb6d485fa/apes-115.zip?rlkey=4hza000j7btue6qwnxvnid5gb&dl=1"

      - name: Set up apes maf cache
        id: cache-apes-data-maf
        uses: actions/cache@v3
        with:
          path: tests/data
          key: ${{ runner.os }}-apes-maf-v3-${{ hashFiles('tests/data/apes-115-maf.zip') }}
          restore-keys: |
            ${{ runner.os }}-apes-maf-v3-

      - name: Check apes maf cache status
        run: |
          echo "Cache hit: ${{ steps.cache-apes-data-maf.outputs.cache-hit }} ***"

      - name: Download apes maf data file
        if: steps.cache-apes-data-maf.outputs.cache-hit != 'true'
        run: |
          curl -L -o tests/data/apes-115-maf.zip "https://www.dropbox.com/scl/fi/2wmle5kzjdqralppvddsr/apes-115-maf.zip?rlkey=u1hbfo0jqwhfkfukntgx5tbfn&dl=1"

      - name: Unzip data files
        run: |
          cd tests/data
          unzip -o -q small-115.zip
          unzip -o -q apes-115.zip
          unzip -o -q apes-115-maf.zip

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Check the lockfile is current
        run: uv lock --check

      - name: Install nox
        run: uv tool install nox

      - name: "Run nox for ${{ matrix.python-version }}"
        run: |
          nox -s test-${{ matrix.python-version }} -- -m 'not internet'


  build:
    name: Build wheel and sdist
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build sdist and wheel
        run: uv build

      - name: Upload sdist and wheel
        uses: actions/upload-artifact@v4
        with:
          name: eti-wheel-sdist
          path: |
            ./dist/*.whl
            ./dist/*.tar.gz
  
  release_test:
    name: Release to Test PyPI
    needs: [build]
    environment: release_test
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download sdist and wheel
        uses: actions/download-artifact@v4
        with:
          name: eti-wheel-sdist
          path: ./dist

      - name: Publish package distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  
  release:
    name: Release to PyPI
    needs: release_test
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download sdist and wheel
        uses: actions/download-artifact@v4
        with:
          name: eti-wheel-sdist
          path: ./dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1